### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by vegetable233** [verlab/accelerated_features#69] opened 2024-10-04 02:34 UTC
Your work is very innteresting. When the evaluation code will be released？

**Comment by cw314** [comment] 2024-10-08 02:20
Yes, this work is perfect. I don't know when the evaluation code of the project will be released. I really need the evaluation code.

**Comment by xtcpete** [comment] 2024-10-13 06:40
The work is truly inspiring. However, I was unable to reproduce the results reported in the paper. I'm not sure if I'm doing the correct way. Could you please release the evaluation code?

**Comment by guipotje** [comment] 2024-10-27 20:58
Hello!

Apologies for the delay in releasing the evaluation code. We carefully refactored it to ensure easy usability for everyone.

The evaluation for MegaDepth and ScanNet is now available. Please submit a new request if you have further questions.

**Closed by guipotje** 2024-10-27 20:58 UTC
